# Generated by Django 2.2.11 on 2020-03-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="user",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
